// Generated by logos-lidl-gen from the `sdk_test_provider_module` LIDL contract — do not edit.
//
// Typed caller + event subscribers over logos_rust_sdk's lp_* consumer.

use logos_rust_sdk::{EventData, EventSubscription, LogosError, LogosModuleSDK, PluginProxy};

pub struct SdkTestProviderModuleClient {
    proxy: PluginProxy,
}

impl SdkTestProviderModuleClient {
    /// Client bound to the contract's own module name (`sdk_test_provider_module`) —
    /// the concrete-dependency pattern.
    pub fn new() -> Self {
        Self { proxy: LogosModuleSDK::new().plugin("sdk_test_provider_module") }
    }

    /// Bind the same typed surface to ANY provider chosen at runtime —
    /// the interface-dependency pattern: the contract names the shape,
    /// the caller names the module.
    pub fn bind(module_name: &str) -> Self {
        Self { proxy: LogosModuleSDK::new().plugin(module_name) }
    }

    pub fn add(&self, a: i64, b: i64) -> Result<i64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(a), serde_json::Value::from(b)]);
        let value = self.proxy.call_json("add", &args)?;
        value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))
    }

    /// [`Self::add`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::add`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn add_with_timeout(&self, a: i64, b: i64, timeout: std::time::Duration) -> Result<i64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(a), serde_json::Value::from(b)]);
        let value = self.proxy.call_json_with_timeout("add", &args, timeout)?;
        value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))
    }

    /// Async twin of [`Self::add`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `addAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn add_async<F>(&self, a: i64, b: i64, callback: F)
    where
        F: FnOnce(Result<i64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(a), serde_json::Value::from(b)]);
        self.proxy.call_json_async("add", &args, move |result| {
            callback(result.and_then(|value| value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))));
        });
    }

    /// [`Self::add_async`] with a per-call timeout — the async half of
    /// [`Self::add_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::add_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn add_async_with_timeout<F>(&self, a: i64, b: i64, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<i64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(a), serde_json::Value::from(b)]);
        self.proxy.call_json_async_with_timeout("add", &args, timeout, move |result| {
            callback(result.and_then(|value| value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))));
        });
    }

    pub fn emit_blob(&self, size: i64) -> Result<i64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(size)]);
        let value = self.proxy.call_json("emit_blob", &args)?;
        value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))
    }

    /// [`Self::emit_blob`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::emit_blob`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn emit_blob_with_timeout(&self, size: i64, timeout: std::time::Duration) -> Result<i64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(size)]);
        let value = self.proxy.call_json_with_timeout("emit_blob", &args, timeout)?;
        value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))
    }

    /// Async twin of [`Self::emit_blob`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `emit_blobAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn emit_blob_async<F>(&self, size: i64, callback: F)
    where
        F: FnOnce(Result<i64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(size)]);
        self.proxy.call_json_async("emit_blob", &args, move |result| {
            callback(result.and_then(|value| value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))));
        });
    }

    /// [`Self::emit_blob_async`] with a per-call timeout — the async half of
    /// [`Self::emit_blob_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::emit_blob_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn emit_blob_async_with_timeout<F>(&self, size: i64, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<i64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(size)]);
        self.proxy.call_json_async_with_timeout("emit_blob", &args, timeout, move |result| {
            callback(result.and_then(|value| value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))));
        });
    }

    /// Block for `ms` milliseconds, then echo `ms` back. The fixture a per-call timeout is measured against: a caller that outlives its timeout must come back at the timeout, not at `ms`.
    pub fn sleep(&self, ms: i64) -> Result<i64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(ms)]);
        let value = self.proxy.call_json("sleep", &args)?;
        value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))
    }

    /// [`Self::sleep`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::sleep`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn sleep_with_timeout(&self, ms: i64, timeout: std::time::Duration) -> Result<i64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(ms)]);
        let value = self.proxy.call_json_with_timeout("sleep", &args, timeout)?;
        value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))
    }

    /// Async twin of [`Self::sleep`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `sleepAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn sleep_async<F>(&self, ms: i64, callback: F)
    where
        F: FnOnce(Result<i64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(ms)]);
        self.proxy.call_json_async("sleep", &args, move |result| {
            callback(result.and_then(|value| value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))));
        });
    }

    /// [`Self::sleep_async`] with a per-call timeout — the async half of
    /// [`Self::sleep_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::sleep_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn sleep_async_with_timeout<F>(&self, ms: i64, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<i64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(ms)]);
        self.proxy.call_json_async_with_timeout("sleep", &args, timeout, move |result| {
            callback(result.and_then(|value| value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))));
        });
    }

    /// Subscribe to the `blobReady` event. Payload arrives as a JSON array of [seq: int, payload: bstr];
    /// decode each received item with [`Self::decode_blob_ready`]. The returned
    /// subscription owns its client share — move it into a listener
    /// thread and iterate it; drop it to unsubscribe.
    pub fn on_blob_ready(&mut self) -> Result<EventSubscription, LogosError> {
        self.proxy.on("blobReady")
    }

    /// Decode a received `blobReady` payload into its typed form.
    /// Returns None if the payload doesn't match the contract.
    pub fn decode_blob_ready(ev: &EventData) -> Option<BlobReadyEvent> {
        let arr = ev.data.as_array()?;
        if arr.len() < 2 { return None; }
        Some(BlobReadyEvent {
            seq: arr[0].as_i64()?,
            payload: logos_rust_sdk::bytes::decode(&arr[1])?,
        })
    }
}

/// Typed payload of the `blobReady` event.
#[derive(Debug, Clone)]
pub struct BlobReadyEvent {
    pub seq: i64,
    pub payload: Vec<u8>,
}

impl Default for SdkTestProviderModuleClient {
    fn default() -> Self {
        Self::new()
    }
}
