//! Basic Rust provider on the builder-driven cdylib path (no build.rs). The
//! module-impl C ABI scaffold + the typed `emit_computed` event emitter are
//! generated by the builder from the .lidl; the author writes the trait impl.

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/generated/provider_gen.rs"));

#[derive(Default)]
struct CalcImpl;

impl RustCalcModule for CalcImpl {
    fn add(&mut self, a: i64, b: i64) -> i64 {
        let total = a + b;
        emit_computed(total); // typed event emitter (generated from the contract)
        total
    }

    fn multiply(&mut self, a: i64, b: i64) -> i64 {
        let total = a.saturating_mul(b);
        emit_computed(total);
        total
    }
}

#[no_mangle]
pub extern "Rust" fn logos_module_install() {
    install::<CalcImpl>();
}
