// Generated by logos-lidl-gen --provider from the `sdk_test_provider_module` LIDL contract — do not edit.
//
// The common module-impl C ABI (logos_module_impl.h) around a Rust impl:
// implement `SdkTestProviderModule` on your type and define the install hook:
//
//     #[no_mangle]
//     pub extern "Rust" fn logos_module_install() { install::<YourImpl>(); }
//
// The first dispatch invokes it lazily — a plain symbol reference, so
// no ctor/init-section tricks are needed for static linking.

use std::ffi::{c_char, c_int, c_void, CStr, CString};
use std::sync::Mutex;

/// This module's own name, from the LIDL contract.
///
/// The ORIGIN of every outbound call this image makes: it is what
/// capability_module checks against its known-caller roster and the
/// target's access policy, what the target files the minted token
/// under, and what a callee's `current_caller()` reports.
pub const LOGOS_MODULE_NAME: &str = "sdk_test_provider_module";

#[derive(Debug, Clone, Default)]
pub struct RustModuleContext {
    pub module_path: String,
    pub instance_id: String,
    pub instance_persistence_path: String,
}

static CONTEXT: Mutex<Option<RustModuleContext>> = Mutex::new(None);

/// The module identity/context stamped by the host (None before
/// set_context — mirrors LogosModuleContext::isContextReady()).
pub fn context() -> Option<RustModuleContext> {
    CONTEXT.lock().unwrap().clone()
}

type EmitCb = extern "C" fn(*const c_char, *const c_char, *mut c_void);
struct EmitState {
    cb: Option<(EmitCb, usize)>,
}
unsafe impl Send for EmitState {}
static EMIT: Mutex<EmitState> = Mutex::new(EmitState { cb: None });

fn emit_event(name: &str, payload: &serde_json::Value) {
    let state = EMIT.lock().unwrap();
    if let Some((cb, ud)) = state.cb {
        let name_c = CString::new(name).unwrap_or_default();
        let json_c = CString::new(payload.to_string()).unwrap_or_default();
        cb(name_c.as_ptr(), json_c.as_ptr(), ud as *mut c_void);
    }
}

/// Typed emitter for the `blobReady` event.
pub fn emit_blob_ready(seq: i64, payload: &[u8]) {
    let mut __logos_args: Vec<serde_json::Value> = Vec::new();
    __logos_args.push(serde_json::Value::from(seq));
    __logos_args.push(logos_rust_sdk::bytes::encode(payload));
    emit_event("blobReady", &serde_json::Value::Array(__logos_args));
}

pub trait SdkTestProviderModule: 'static {
    /// One-time setup hook: fires after the host has stamped the module
    /// context (path / instance id / persistence path) and before the
    /// first method dispatch — the Rust analog of C++'s
    /// LogosModuleContext::onContextReady().
    fn on_context_ready(&mut self, _ctx: &RustModuleContext) {}

    /// Called when the host is about to unload this module, before the
    /// implementation is dropped. Return `Synchronous` (the default)
    /// when teardown finished inline, or `Asynchronous` to keep the
    /// host waiting until `logos_rust_sdk::unload_finished()` is
    /// called. The host enforces a grace period either way.
    fn about_to_unload(&mut self) -> logos_rust_sdk::Shutdown {
        logos_rust_sdk::Shutdown::Synchronous
    }

    fn add(&mut self, a: i64, b: i64) -> i64;
    fn emit_blob(&mut self, size: i64) -> i64;
    fn sleep(&mut self, ms: i64) -> i64;
}

type DispatchFn = fn(&str, &[serde_json::Value]) -> Option<serde_json::Value>;
type EnsureFn = fn(bool);
// Reaches the author's impl from the teardown C export, which is a
// free function with no `T` -- exactly why `dispatch` is reached
// this way too.
type AboutToUnloadFn = fn() -> i32;
struct Registered {
    dispatch: DispatchFn,
    ensure: EnsureFn,
    // Read only by the teardown export, which is emitted for
    // protocol >= 0.5; an older module registers the hook and
    // never calls it.
    #[allow(dead_code)]
    about_to_unload: AboutToUnloadFn,
}
static REGISTERED: Mutex<Option<Registered>> = Mutex::new(None);
// A concurrency:"single" module runs entirely on one thread (its
// subprocess event loop): install / on_context_ready / dispatch all touch
// INSTANCE from that thread, so the impl never crosses threads and need
// not be Send. This single-threaded Sync wrapper lets a non-Send impl
// live in a static (cf. the EmitState unsafe impl above).
struct SingleInstance(Mutex<Option<Box<dyn std::any::Any>>>);
unsafe impl Sync for SingleInstance {}
static INSTANCE: SingleInstance = SingleInstance(Mutex::new(None));
static HOOK_FIRED: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);

/// Install `T` as the module implementation (Default-constructed once).
///
/// `on_context_ready` fires AT MODULE LOAD — as soon as the host has
/// delivered both the context (set_context) and the event plumbing
/// (set_emit_callback), which the glue does during registration,
/// before the module is published for inbound calls. This matches
/// C++'s onContextReady-in-onInit semantics: subscriptions, outbound
/// calls and typed emission all work from the hook without waiting
/// for a first inbound dispatch. (For hosts that never wire an emit
/// callback, the hook still fires before the first dispatch.)
pub fn install<T: SdkTestProviderModule + Default>() {
    fn ensure_impl<T: SdkTestProviderModule + Default>(require_emit: bool) {
        let mut guard = INSTANCE.0.lock().unwrap();
        if guard.is_none() {
            *guard = Some(Box::new(T::default()));
        }
        if HOOK_FIRED.load(std::sync::atomic::Ordering::SeqCst) {
            return;
        }
        let Some(ctx) = context() else { return; };
        if require_emit && EMIT.lock().unwrap().cb.is_none() {
            return;
        }
        if let Some(imp) = guard.as_mut().unwrap().downcast_mut::<T>() {
            HOOK_FIRED.store(true, std::sync::atomic::Ordering::SeqCst);
            imp.on_context_ready(&ctx);
        }
    }
    fn about_to_unload_impl<T: SdkTestProviderModule + Default>() -> i32 {
        // No instance means nothing was ever constructed, so there is
        // nothing to tear down: Synchronous, and the host proceeds.
        let mut guard = INSTANCE.0.lock().unwrap();
        let Some(any) = guard.as_mut() else { return 0 };
        let Some(imp) = any.downcast_mut::<T>() else { return 0 };
        match imp.about_to_unload() {
            logos_rust_sdk::Shutdown::Asynchronous => 1,
            logos_rust_sdk::Shutdown::Synchronous => 0,
        }
    }
    fn dispatch_impl<T: SdkTestProviderModule + Default>(method: &str, args: &[serde_json::Value]) -> Option<serde_json::Value> {
        let mut guard = INSTANCE.0.lock().unwrap();
        if guard.is_none() {
            *guard = Some(Box::new(T::default()));
        }
        let imp: &mut T = guard.as_mut().unwrap().downcast_mut::<T>()?;
        match method {
            "add" => {
                if args.len() < 2 { return Some(logos_rust_sdk::args::invalid_args("sdk_test_provider_module", 2, args.len())); }
                let __logos_a0 = match logos_rust_sdk::args::as_i64(args, 0) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("sdk_test_provider_module", &e)) };
                let __logos_a1 = match logos_rust_sdk::args::as_i64(args, 1) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("sdk_test_provider_module", &e)) };
                let result = imp.add(__logos_a0, __logos_a1);
                Some(serde_json::Value::from(result))
            }
            "emit_blob" => {
                if args.len() < 1 { return Some(logos_rust_sdk::args::invalid_args("sdk_test_provider_module", 1, args.len())); }
                let __logos_a0 = match logos_rust_sdk::args::as_i64(args, 0) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("sdk_test_provider_module", &e)) };
                let result = imp.emit_blob(__logos_a0);
                Some(serde_json::Value::from(result))
            }
            "sleep" => {
                if args.len() < 1 { return Some(logos_rust_sdk::args::invalid_args("sdk_test_provider_module", 1, args.len())); }
                let __logos_a0 = match logos_rust_sdk::args::as_i64(args, 0) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("sdk_test_provider_module", &e)) };
                let result = imp.sleep(__logos_a0);
                Some(serde_json::Value::from(result))
            }
            "name" => {
                                     let result = "sdk_test_provider_module".to_string();
                                     Some(serde_json::Value::from(result))
                                 }
            "version" => {
                                     let result = "0.1.0".to_string();
                                     Some(serde_json::Value::from(result))
                                 }
            _ => None,
        }
    }
    *REGISTERED.lock().unwrap() = Some(Registered {
        dispatch: dispatch_impl::<T>,
        ensure: ensure_impl::<T>,
        about_to_unload: about_to_unload_impl::<T>,
    });
}

/// Run the author's install hook (once) and give the ready-latch a
/// chance to fire `on_context_ready`. Called from every C-ABI entry
/// point: set_context / set_emit_callback latch on full wiring;
/// dispatch passes require_emit = false as the no-event-host fallback.
fn ensure_ready(require_emit: bool) {
    // FIRST, and before the author's install hook can construct
    // anything: tell the SDK the name this image announces when it
    // calls out. Every generated path that reaches author code runs
    // through here -- install/T::default, on_context_ready, dispatch,
    // and (transitively) about_to_unload, which answers 0 unless
    // install already ran -- so the origin is set before the first
    // outbound client exists. Without a name the SDK announces
    // nothing and the capability handshake fails closed; with the
    // wrong one ("core") it authorized as the host. The SDK also
    // keys its client cache by origin, so even a client built before
    // this ran cannot be reused after it. Idempotent: a OnceLock set.
    logos_rust_sdk::set_module_origin(LOGOS_MODULE_NAME);
    if REGISTERED.lock().unwrap().is_none() {
        unsafe { __logos_install_hook::logos_module_install() };
    }
    let ensure = REGISTERED.lock().unwrap().as_ref().map(|r| r.ensure);
    if let Some(f) = ensure {
        f(require_emit);
    }
}

mod __logos_install_hook {
    // Defined by the module author (a #[no_mangle] fn at crate root):
    // call `install::<YourImpl>()` once. Scoped inside a module so the
    // declaration and the author's definition don't collide by path;
    // they meet at the symbol level. Referenced (not just expected) so
    // static linking always pulls the author's object in — invoked
    // lazily on first dispatch.
    extern "Rust" {
        pub(super) fn logos_module_install();
    }
}

fn to_c_string(s: String) -> *mut c_char {
    CString::new(s).map(CString::into_raw).unwrap_or(std::ptr::null_mut())
}

#[no_mangle]
pub extern "C" fn logos_module_dispatch(method: *const c_char, args_json: *const c_char) -> *mut c_char {
    if method.is_null() { return std::ptr::null_mut(); }
    let method = unsafe { CStr::from_ptr(method) }.to_string_lossy().into_owned();
    let args: Vec<serde_json::Value> = if args_json.is_null() {
        Vec::new()
    } else {
        let raw = unsafe { CStr::from_ptr(args_json) }.to_string_lossy();
        match serde_json::from_str::<serde_json::Value>(&raw) {
            Ok(serde_json::Value::Array(a)) => a,
            _ => return std::ptr::null_mut(),
        }
    };
    ensure_ready(false);
    // Copy the dispatch fn pointer out and RELEASE the REGISTERED
    // lock BEFORE running the handler. A concurrency:"multi" module's
    // glue calls this from worker threads; holding the mutex across
    // the handler would serialize every call (peak overlap 1).
    // dispatch_impl resolves the instance internally (a cloned Arc in
    // multi mode, the boxed instance behind the SingleInstance mutex in
    // single mode) without holding REGISTERED, so dropping the lock here
    // first is safe. Same release-before-call shape as ensure_ready.
    let dispatch = match REGISTERED.lock().unwrap().as_ref() { Some(r) => r.dispatch, None => return std::ptr::null_mut() };
    match dispatch(&method, &args) {
        Some(value) => to_c_string(value.to_string()),
        None => std::ptr::null_mut(),
    }
}

#[no_mangle]
pub extern "C" fn logos_module_get_methods() -> *mut c_char {
    to_c_string("[{\"isInvokable\":true,\"name\":\"add\",\"parameters\":[{\"name\":\"a\",\"type\":\"int\"},{\"name\":\"b\",\"type\":\"int\"}],\"returnType\":\"int\",\"signature\":\"add(int,int)\"},{\"isInvokable\":true,\"name\":\"emit_blob\",\"parameters\":[{\"name\":\"size\",\"type\":\"int\"}],\"returnType\":\"int\",\"signature\":\"emit_blob(int)\"},{\"isInvokable\":true,\"name\":\"sleep\",\"parameters\":[{\"name\":\"ms\",\"type\":\"int\"}],\"returnType\":\"int\",\"signature\":\"sleep(int)\"},{\"isInvokable\":true,\"name\":\"name\",\"returnType\":\"QString\",\"signature\":\"name()\"},{\"isInvokable\":true,\"name\":\"version\",\"returnType\":\"QString\",\"signature\":\"version()\"},{\"name\":\"blobReady\",\"parameters\":[{\"name\":\"seq\",\"type\":\"int\"},{\"name\":\"payload\",\"type\":\"QByteArray\"}],\"signature\":\"blobReady(int,QByteArray)\",\"type\":\"event\"}]".to_string())
}

#[no_mangle]
pub extern "C" fn logos_module_set_context(
    module_path: *const c_char,
    instance_id: *const c_char,
    instance_persistence_path: *const c_char,
) {
    fn s(p: *const c_char) -> String {
        if p.is_null() { String::new() } else { unsafe { CStr::from_ptr(p) }.to_string_lossy().into_owned() }
    }
    *CONTEXT.lock().unwrap() = Some(RustModuleContext {
        module_path: s(module_path),
        instance_id: s(instance_id),
        instance_persistence_path: s(instance_persistence_path),
    });
    ensure_ready(true);
}

#[no_mangle]
pub extern "C" fn logos_module_set_emit_callback(cb: Option<EmitCb>, user_data: *mut c_void) {
    EMIT.lock().unwrap().cb = cb.map(|f| (f, user_data as usize));
    ensure_ready(true);
}

static TOKENS: Mutex<Vec<(String, String)>> = Mutex::new(Vec::new());

#[no_mangle]
pub extern "C" fn logos_module_accept_token(module_name: *const c_char, token: *const c_char) -> c_int {
    if module_name.is_null() || token.is_null() { return -1; }
    let name = unsafe { CStr::from_ptr(module_name) }.to_string_lossy().into_owned();
    let tok = unsafe { CStr::from_ptr(token) }.to_string_lossy().into_owned();
    // THE OUTBOUND DOOR. Hand the host-issued token to the SDK's
    // protocol stack so this module's *outbound* calls authenticate —
    // the same stack the typed client wrappers invoke through.
    //
    // ONE MEANING ONLY, as of protocol 0.8: the module's OWN anchor,
    // seeded by the Qt glue's onInit. A CALLER's token goes through
    // logos_module_accept_inbound_token instead. Do not merge them —
    // one value written through the wrong door made every capability
    // grant silently bidirectional.
    logos_rust_sdk::save_token(&name, &tok);
    TOKENS.lock().unwrap().push((name, tok));
    0
}

/// The logos-protocol semver this module was built against
/// (stamped at generation time by the build; never minted here).
#[no_mangle]
pub extern "C" fn logos_module_get_protocol_version() -> *const c_char {
    static VERSION: &str = "0.5.0\0";
    VERSION.as_ptr() as *const c_char
}

#[no_mangle]
pub extern "C" fn logos_module_string_free(s: *mut c_char) {
    if !s.is_null() {
        unsafe { drop(CString::from_raw(s)) };
    }
}

#[no_mangle]
pub extern "C" fn logos_module_grant_host_services(services_json: *const c_char) -> c_int {
    if services_json.is_null() { return -1; }
    unsafe { logos_rust_sdk::grant_host_services(services_json) }
}

#[no_mangle]
pub extern "C" fn logos_module_set_unload_done_callback(
    cb: Option<logos_rust_sdk::UnloadDoneCb>,
    user_data: *mut std::os::raw::c_void,
) {
    logos_rust_sdk::set_unload_done_callback(cb, user_data);
}

/// Ask the impl whether it is ready to be unloaded: 0 = Synchronous
/// (proceed), 1 = Asynchronous (wait for unload_finished()).
///
/// A module that was never installed answers 0: there is no instance, so
/// there is nothing to tear down and nothing for the host to wait on.
#[no_mangle]
pub extern "C" fn logos_module_about_to_unload() -> c_int {
    let hook = REGISTERED.lock().unwrap().as_ref().map(|r| r.about_to_unload);
    match hook {
        Some(f) => f(),
        None => 0,
    }
}
