// Generated by logos-lidl-gen from the `sensor_module` LIDL contract — do not edit.
//
// Typed caller + event subscribers over logos_rust_sdk's lp_* consumer.

use logos_rust_sdk::{EventData, EventSubscription, LogosError, LogosModuleSDK, PluginProxy, RestartPolicy, SubStatus};

pub struct SensorModuleClient {
    proxy: PluginProxy,
}

impl SensorModuleClient {
    /// Client bound to the contract's own module name (`sensor_module`) —
    /// the concrete-dependency pattern.
    pub fn new() -> Self {
        Self { proxy: LogosModuleSDK::new().plugin("sensor_module") }
    }

    /// Bind the same typed surface to ANY provider chosen at runtime —
    /// the interface-dependency pattern: the contract names the shape,
    /// the caller names the module.
    pub fn bind(module_name: &str) -> Self {
        Self { proxy: LogosModuleSDK::new().plugin(module_name) }
    }

    /// Returns the latest temperature reading in degrees Celsius.
    pub fn temperature(&self) -> Result<f64, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json("temperature", &args)?;
        value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))
    }

    /// [`Self::temperature`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::temperature`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn temperature_with_timeout(&self, timeout: std::time::Duration) -> Result<f64, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json_with_timeout("temperature", &args, timeout)?;
        value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))
    }

    /// Async twin of [`Self::temperature`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `temperatureAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn temperature_async<F>(&self, callback: F)
    where
        F: FnOnce(Result<f64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async("temperature", &args, move |result| {
            callback(result.and_then(|value| value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))));
        });
    }

    /// [`Self::temperature_async`] with a per-call timeout — the async half of
    /// [`Self::temperature_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::temperature_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn temperature_async_with_timeout<F>(&self, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<f64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async_with_timeout("temperature", &args, timeout, move |result| {
            callback(result.and_then(|value| value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))));
        });
    }

    /// Enables or disables the sensor.
    /// Returns the new enabled state.
    pub fn enable(&self, on: bool) -> Result<bool, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(on)]);
        let value = self.proxy.call_json("enable", &args)?;
        value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))
    }

    /// [`Self::enable`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::enable`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn enable_with_timeout(&self, on: bool, timeout: std::time::Duration) -> Result<bool, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(on)]);
        let value = self.proxy.call_json_with_timeout("enable", &args, timeout)?;
        value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))
    }

    /// Async twin of [`Self::enable`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `enableAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn enable_async<F>(&self, on: bool, callback: F)
    where
        F: FnOnce(Result<bool, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(on)]);
        self.proxy.call_json_async("enable", &args, move |result| {
            callback(result.and_then(|value| value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))));
        });
    }

    /// [`Self::enable_async`] with a per-call timeout — the async half of
    /// [`Self::enable_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::enable_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn enable_async_with_timeout<F>(&self, on: bool, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<bool, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(on)]);
        self.proxy.call_json_async_with_timeout("enable", &args, timeout, move |result| {
            callback(result.and_then(|value| value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))));
        });
    }

    /// Renames the sensor channel.
    pub fn rename(&self, id: u64, name: &str) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(name)]);
        let value = self.proxy.call_json("rename", &args)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// [`Self::rename`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::rename`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn rename_with_timeout(&self, id: u64, name: &str, timeout: std::time::Duration) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(name)]);
        let value = self.proxy.call_json_with_timeout("rename", &args, timeout)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// Async twin of [`Self::rename`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `renameAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn rename_async<F>(&self, id: u64, name: &str, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(name)]);
        self.proxy.call_json_async("rename", &args, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// [`Self::rename_async`] with a per-call timeout — the async half of
    /// [`Self::rename_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::rename_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn rename_async_with_timeout<F>(&self, id: u64, name: &str, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(name)]);
        self.proxy.call_json_async_with_timeout("rename", &args, timeout, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// Calibrates a channel with an offset and a human-readable label.
    pub fn calibrate(&self, id: u64, offset: f64, label: &str) -> Result<bool, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(offset), serde_json::Value::from(label)]);
        let value = self.proxy.call_json("calibrate", &args)?;
        value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))
    }

    /// [`Self::calibrate`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::calibrate`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn calibrate_with_timeout(&self, id: u64, offset: f64, label: &str, timeout: std::time::Duration) -> Result<bool, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(offset), serde_json::Value::from(label)]);
        let value = self.proxy.call_json_with_timeout("calibrate", &args, timeout)?;
        value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))
    }

    /// Async twin of [`Self::calibrate`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `calibrateAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn calibrate_async<F>(&self, id: u64, offset: f64, label: &str, callback: F)
    where
        F: FnOnce(Result<bool, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(offset), serde_json::Value::from(label)]);
        self.proxy.call_json_async("calibrate", &args, move |result| {
            callback(result.and_then(|value| value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))));
        });
    }

    /// [`Self::calibrate_async`] with a per-call timeout — the async half of
    /// [`Self::calibrate_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::calibrate_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn calibrate_async_with_timeout<F>(&self, id: u64, offset: f64, label: &str, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<bool, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(offset), serde_json::Value::from(label)]);
        self.proxy.call_json_async_with_timeout("calibrate", &args, timeout, move |result| {
            callback(result.and_then(|value| value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))));
        });
    }

    /// Records a reading and returns the new sample count.
    pub fn record(&self, id: u64, value: f64, note: &str, valid: bool) -> Result<i64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(value), serde_json::Value::from(note), serde_json::Value::from(valid)]);
        let value = self.proxy.call_json("record", &args)?;
        value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))
    }

    /// [`Self::record`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::record`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn record_with_timeout(&self, id: u64, value: f64, note: &str, valid: bool, timeout: std::time::Duration) -> Result<i64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(value), serde_json::Value::from(note), serde_json::Value::from(valid)]);
        let value = self.proxy.call_json_with_timeout("record", &args, timeout)?;
        value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))
    }

    /// Async twin of [`Self::record`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `recordAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn record_async<F>(&self, id: u64, value: f64, note: &str, valid: bool, callback: F)
    where
        F: FnOnce(Result<i64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(value), serde_json::Value::from(note), serde_json::Value::from(valid)]);
        self.proxy.call_json_async("record", &args, move |result| {
            callback(result.and_then(|value| value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))));
        });
    }

    /// [`Self::record_async`] with a per-call timeout — the async half of
    /// [`Self::record_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::record_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn record_async_with_timeout<F>(&self, id: u64, value: f64, note: &str, valid: bool, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<i64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(value), serde_json::Value::from(note), serde_json::Value::from(valid)]);
        self.proxy.call_json_async_with_timeout("record", &args, timeout, move |result| {
            callback(result.and_then(|value| value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))));
        });
    }

    /// Flashes raw firmware bytes and echoes back the stored image.
    pub fn firmware(&self, image: &[u8]) -> Result<Vec<u8>, LogosError> {
        let args = serde_json::Value::Array(vec![logos_rust_sdk::bytes::encode(image)]);
        let value = self.proxy.call_json("firmware", &args)?;
        logos_rust_sdk::bytes::decode(&value).ok_or_else(|| logos_rust_sdk::LogosError::JsonError("expected {\"_bytes\":...} payload".to_string()))
    }

    /// [`Self::firmware`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::firmware`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn firmware_with_timeout(&self, image: &[u8], timeout: std::time::Duration) -> Result<Vec<u8>, LogosError> {
        let args = serde_json::Value::Array(vec![logos_rust_sdk::bytes::encode(image)]);
        let value = self.proxy.call_json_with_timeout("firmware", &args, timeout)?;
        logos_rust_sdk::bytes::decode(&value).ok_or_else(|| logos_rust_sdk::LogosError::JsonError("expected {\"_bytes\":...} payload".to_string()))
    }

    /// Async twin of [`Self::firmware`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `firmwareAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn firmware_async<F>(&self, image: &[u8], callback: F)
    where
        F: FnOnce(Result<Vec<u8>, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![logos_rust_sdk::bytes::encode(image)]);
        self.proxy.call_json_async("firmware", &args, move |result| {
            callback(result.and_then(|value| logos_rust_sdk::bytes::decode(&value).ok_or_else(|| logos_rust_sdk::LogosError::JsonError("expected {\"_bytes\":...} payload".to_string()))));
        });
    }

    /// [`Self::firmware_async`] with a per-call timeout — the async half of
    /// [`Self::firmware_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::firmware_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn firmware_async_with_timeout<F>(&self, image: &[u8], timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<Vec<u8>, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![logos_rust_sdk::bytes::encode(image)]);
        self.proxy.call_json_async_with_timeout("firmware", &args, timeout, move |result| {
            callback(result.and_then(|value| logos_rust_sdk::bytes::decode(&value).ok_or_else(|| logos_rust_sdk::LogosError::JsonError("expected {\"_bytes\":...} payload".to_string()))));
        });
    }

    /// Resolves a batch of channel ids to their labels.
    pub fn labels(&self, ids: &[u64]) -> Result<Vec<String>, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::Array(ids.iter().map(|__e| serde_json::json!(__e)).collect())]);
        let value = self.proxy.call_json("labels", &args)?;
        (|| Some((&value).as_array()?.iter().map(|__e| Some(__e.as_str()?.to_string())).collect::<Option<Vec<_>>>()?))().ok_or_else(|| logos_rust_sdk::LogosError::JsonError("result does not match the declared collection type".to_string()))
    }

    /// [`Self::labels`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::labels`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn labels_with_timeout(&self, ids: &[u64], timeout: std::time::Duration) -> Result<Vec<String>, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::Array(ids.iter().map(|__e| serde_json::json!(__e)).collect())]);
        let value = self.proxy.call_json_with_timeout("labels", &args, timeout)?;
        (|| Some((&value).as_array()?.iter().map(|__e| Some(__e.as_str()?.to_string())).collect::<Option<Vec<_>>>()?))().ok_or_else(|| logos_rust_sdk::LogosError::JsonError("result does not match the declared collection type".to_string()))
    }

    /// Async twin of [`Self::labels`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `labelsAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn labels_async<F>(&self, ids: &[u64], callback: F)
    where
        F: FnOnce(Result<Vec<String>, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::Array(ids.iter().map(|__e| serde_json::json!(__e)).collect())]);
        self.proxy.call_json_async("labels", &args, move |result| {
            callback(result.and_then(|value| (|| Some((&value).as_array()?.iter().map(|__e| Some(__e.as_str()?.to_string())).collect::<Option<Vec<_>>>()?))().ok_or_else(|| logos_rust_sdk::LogosError::JsonError("result does not match the declared collection type".to_string()))));
        });
    }

    /// [`Self::labels_async`] with a per-call timeout — the async half of
    /// [`Self::labels_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::labels_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn labels_async_with_timeout<F>(&self, ids: &[u64], timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<Vec<String>, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::Array(ids.iter().map(|__e| serde_json::json!(__e)).collect())]);
        self.proxy.call_json_async_with_timeout("labels", &args, timeout, move |result| {
            callback(result.and_then(|value| (|| Some((&value).as_array()?.iter().map(|__e| Some(__e.as_str()?.to_string())).collect::<Option<Vec<_>>>()?))().ok_or_else(|| logos_rust_sdk::LogosError::JsonError("result does not match the declared collection type".to_string()))));
        });
    }

    /// Computes the mean of a batch of samples.
    pub fn average(&self, samples: &[f64]) -> Result<f64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::Array(samples.iter().map(|__e| serde_json::json!(__e)).collect())]);
        let value = self.proxy.call_json("average", &args)?;
        value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))
    }

    /// [`Self::average`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::average`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn average_with_timeout(&self, samples: &[f64], timeout: std::time::Duration) -> Result<f64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::Array(samples.iter().map(|__e| serde_json::json!(__e)).collect())]);
        let value = self.proxy.call_json_with_timeout("average", &args, timeout)?;
        value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))
    }

    /// Async twin of [`Self::average`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `averageAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn average_async<F>(&self, samples: &[f64], callback: F)
    where
        F: FnOnce(Result<f64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::Array(samples.iter().map(|__e| serde_json::json!(__e)).collect())]);
        self.proxy.call_json_async("average", &args, move |result| {
            callback(result.and_then(|value| value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))));
        });
    }

    /// [`Self::average_async`] with a per-call timeout — the async half of
    /// [`Self::average_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::average_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn average_async_with_timeout<F>(&self, samples: &[f64], timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<f64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::Array(samples.iter().map(|__e| serde_json::json!(__e)).collect())]);
        self.proxy.call_json_async_with_timeout("average", &args, timeout, move |result| {
            callback(result.and_then(|value| value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))));
        });
    }

    /// Resets a channel; returns a structured success/error result.
    pub fn reset(&self, id: &str) -> Result<serde_json::Value, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id)]);
        let value = self.proxy.call_json("reset", &args)?;
        Ok(value)
    }

    /// [`Self::reset`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::reset`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn reset_with_timeout(&self, id: &str, timeout: std::time::Duration) -> Result<serde_json::Value, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id)]);
        let value = self.proxy.call_json_with_timeout("reset", &args, timeout)?;
        Ok(value)
    }

    /// Async twin of [`Self::reset`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `resetAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn reset_async<F>(&self, id: &str, callback: F)
    where
        F: FnOnce(Result<serde_json::Value, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id)]);
        self.proxy.call_json_async("reset", &args, move |result| {
            callback(result.and_then(|value| Ok(value)));
        });
    }

    /// [`Self::reset_async`] with a per-call timeout — the async half of
    /// [`Self::reset_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::reset_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn reset_async_with_timeout<F>(&self, id: &str, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<serde_json::Value, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id)]);
        self.proxy.call_json_async_with_timeout("reset", &args, timeout, move |result| {
            callback(result.and_then(|value| Ok(value)));
        });
    }

    /// The module's name, as declared in its metadata.
    pub fn name(&self) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json("name", &args)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// [`Self::name`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::name`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn name_with_timeout(&self, timeout: std::time::Duration) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json_with_timeout("name", &args, timeout)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// Async twin of [`Self::name`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `nameAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn name_async<F>(&self, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async("name", &args, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// [`Self::name_async`] with a per-call timeout — the async half of
    /// [`Self::name_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::name_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn name_async_with_timeout<F>(&self, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async_with_timeout("name", &args, timeout, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// The module's version, as declared in its metadata.
    pub fn version(&self) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json("version", &args)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// [`Self::version`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::version`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn version_with_timeout(&self, timeout: std::time::Duration) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json_with_timeout("version", &args, timeout)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// Async twin of [`Self::version`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `versionAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn version_async<F>(&self, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async("version", &args, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// [`Self::version_async`] with a per-call timeout — the async half of
    /// [`Self::version_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::version_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn version_async_with_timeout<F>(&self, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async_with_timeout("version", &args, timeout, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// The module's canonical LIDL interface document.
    pub fn lidl(&self) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json("lidl", &args)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// [`Self::lidl`] with a per-call timeout: THIS call gives up after
    /// `timeout` instead of waiting for the protocol default (20s).
    /// The bound is threaded down to the call and stored nowhere, so
    /// the next call through the same client — with a different
    /// timeout, or with none — is unaffected.
    ///
    /// Fails with `LogosError::InvalidTimeout` if the duration cannot be
    /// expressed on the protocol ABI (sub-millisecond, or longer than
    /// ~24.8 days). It is refused, never clamped.
    ///
    /// A parallel entry point rather than a parameter on [`Self::lidl`]:
    /// Rust has neither overloading nor default arguments, so the
    /// parameter would break every existing call site. STOPGAP — a later
    /// breaking release folds this back into the single entry point.
    pub fn lidl_with_timeout(&self, timeout: std::time::Duration) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json_with_timeout("lidl", &args, timeout)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// Async twin of [`Self::lidl`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `lidlAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn lidl_async<F>(&self, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async("lidl", &args, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// [`Self::lidl_async`] with a per-call timeout — the async half of
    /// [`Self::lidl_with_timeout`]. The bound applies to THIS call only;
    /// nothing is stored on the client.
    ///
    /// A duration the protocol ABI cannot express (sub-millisecond, or
    /// longer than ~24.8 days) is delivered to `callback` as
    /// `LogosError::InvalidTimeout`, synchronously and with nothing sent,
    /// which is how every other undispatchable async call is reported.
    ///
    /// STOPGAP, like its sync twin: Rust cannot overload
    /// [`Self::lidl_async`], so the bounded form needs its own name until a
    /// breaking release makes `timeout` a parameter of the one entry point.
    pub fn lidl_async_with_timeout<F>(&self, timeout: std::time::Duration, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async_with_timeout("lidl", &args, timeout, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// Watch this module's subscription transitions: `Armed` / `Lost` /
    /// `Held` / `Abandoned`, with the establishment number. `Lost` followed
    /// by `Armed` at a higher generation is the unrecoverable-gap marker.
    ///
    /// Per MODULE, not per event: every subscription here shares the
    /// provider's single handle, so they are lost and restored together.
    pub fn on_subscription_status<F>(&mut self, f: F) -> Result<(), LogosError>
    where
        F: Fn(SubStatus, u64) + Send + Sync + 'static,
    {
        self.proxy.on_subscription_status(f)
    }

    /// 0 = never armed, 1 = the first establishment, N+1 after each one.
    pub fn subscription_generation(&mut self) -> u64 {
        self.proxy.subscription_generation()
    }

    /// `Manual` means "do not RE-arm after a loss", never "do not arm".
    pub fn set_restart_policy(&mut self, policy: RestartPolicy) -> Result<(), LogosError> {
        self.proxy.set_restart_policy(policy)
    }

    /// Revive held subscriptions. Safe from inside the status callback.
    pub fn rearm_subscriptions(&mut self) -> bool {
        self.proxy.rearm_subscriptions()
    }

    /// Fires once the sensor has finished warming up.
    /// Subscribe to the `ready` event. Payload arrives as a JSON array;
    /// decode each received item with [`Self::decode_ready`]. The returned
    /// subscription owns its client share — move it into a listener
    /// thread and iterate it; drop it to unsubscribe.
    pub fn on_ready(&mut self) -> Result<EventSubscription, LogosError> {
        self.proxy.on("ready")
    }

    /// Decode a received `ready` payload into its typed form.
    /// Returns None if the payload doesn't match the contract.
    pub fn decode_ready(ev: &EventData) -> Option<ReadyEvent> {
        let arr = ev.data.as_array()?;
        if arr.len() < 0 { return None; }
        Some(ReadyEvent {
        })
    }

    /// Fires on each new reading with the channel id and value.
    /// Subscribe to the `reading` event. Payload arrives as a JSON array of [id: uint, value: float64];
    /// decode each received item with [`Self::decode_reading`]. The returned
    /// subscription owns its client share — move it into a listener
    /// thread and iterate it; drop it to unsubscribe.
    pub fn on_reading(&mut self) -> Result<EventSubscription, LogosError> {
        self.proxy.on("reading")
    }

    /// Decode a received `reading` payload into its typed form.
    /// Returns None if the payload doesn't match the contract.
    pub fn decode_reading(ev: &EventData) -> Option<ReadingEvent> {
        let arr = ev.data.as_array()?;
        if arr.len() < 2 { return None; }
        Some(ReadingEvent {
            id: (&arr[0]).as_u64()?,
            value: (&arr[1]).as_f64()?,
        })
    }

    /// Fires when a channel faults.
    /// Carries an error code, a message, and whether the fault is fatal.
    /// Subscribe to the `fault` event. Payload arrives as a JSON array of [code: int, message: tstr, fatal: bool];
    /// decode each received item with [`Self::decode_fault`]. The returned
    /// subscription owns its client share — move it into a listener
    /// thread and iterate it; drop it to unsubscribe.
    pub fn on_fault(&mut self) -> Result<EventSubscription, LogosError> {
        self.proxy.on("fault")
    }

    /// Decode a received `fault` payload into its typed form.
    /// Returns None if the payload doesn't match the contract.
    pub fn decode_fault(ev: &EventData) -> Option<FaultEvent> {
        let arr = ev.data.as_array()?;
        if arr.len() < 3 { return None; }
        Some(FaultEvent {
            code: (&arr[0]).as_i64()?,
            message: (&arr[1]).as_str()?.to_string(),
            fatal: (&arr[2]).as_bool()?,
        })
    }
}

/// Typed payload of the `ready` event.
#[derive(Debug, Clone)]
pub struct ReadyEvent {
}

/// Typed payload of the `reading` event.
#[derive(Debug, Clone)]
pub struct ReadingEvent {
    pub id: u64,
    pub value: f64,
}

/// Typed payload of the `fault` event.
#[derive(Debug, Clone)]
pub struct FaultEvent {
    pub code: i64,
    pub message: String,
    pub fatal: bool,
}

impl Default for SensorModuleClient {
    fn default() -> Self {
        Self::new()
    }
}
