// Generated by logos-lidl-gen from the `sensor_module` LIDL contract — do not edit.
//
// Typed caller + event subscribers over logos_rust_sdk's lp_* consumer.

use logos_rust_sdk::{EventData, EventSubscription, LogosError, LogosModuleSDK, PluginProxy};

pub struct SensorModuleClient {
    proxy: PluginProxy,
}

impl SensorModuleClient {
    /// Client bound to the contract's own module name (`sensor_module`) —
    /// the concrete-dependency pattern.
    pub fn new() -> Self {
        Self { proxy: LogosModuleSDK::new().plugin("sensor_module") }
    }

    /// Bind the same typed surface to ANY provider chosen at runtime —
    /// the interface-dependency pattern: the contract names the shape,
    /// the caller names the module.
    pub fn bind(module_name: &str) -> Self {
        Self { proxy: LogosModuleSDK::new().plugin(module_name) }
    }

    /// Returns the latest temperature reading in degrees Celsius.
    pub fn temperature(&self) -> Result<f64, LogosError> {
        let args = serde_json::Value::Array(vec![]);
        let value = self.proxy.call_json("temperature", &args)?;
        value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))
    }

    /// Async twin of [`Self::temperature`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `temperatureAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn temperature_async<F>(&self, callback: F)
    where
        F: FnOnce(Result<f64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![]);
        self.proxy.call_json_async("temperature", &args, move |result| {
            callback(result.and_then(|value| value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))));
        });
    }

    /// Enables or disables the sensor.
    /// Returns the new enabled state.
    pub fn enable(&self, on: bool) -> Result<bool, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(on)]);
        let value = self.proxy.call_json("enable", &args)?;
        value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))
    }

    /// Async twin of [`Self::enable`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `enableAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn enable_async<F>(&self, on: bool, callback: F)
    where
        F: FnOnce(Result<bool, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(on)]);
        self.proxy.call_json_async("enable", &args, move |result| {
            callback(result.and_then(|value| value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))));
        });
    }

    /// Renames the sensor channel.
    pub fn rename(&self, id: u64, name: &str) -> Result<String, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(name)]);
        let value = self.proxy.call_json("rename", &args)?;
        Ok(value.as_str().unwrap_or_default().to_string())
    }

    /// Async twin of [`Self::rename`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `renameAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn rename_async<F>(&self, id: u64, name: &str, callback: F)
    where
        F: FnOnce(Result<String, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(name)]);
        self.proxy.call_json_async("rename", &args, move |result| {
            callback(result.and_then(|value| Ok(value.as_str().unwrap_or_default().to_string())));
        });
    }

    /// Calibrates a channel with an offset and a human-readable label.
    pub fn calibrate(&self, id: u64, offset: f64, label: &str) -> Result<bool, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(offset), serde_json::Value::from(label)]);
        let value = self.proxy.call_json("calibrate", &args)?;
        value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))
    }

    /// Async twin of [`Self::calibrate`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `calibrateAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn calibrate_async<F>(&self, id: u64, offset: f64, label: &str, callback: F)
    where
        F: FnOnce(Result<bool, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(offset), serde_json::Value::from(label)]);
        self.proxy.call_json_async("calibrate", &args, move |result| {
            callback(result.and_then(|value| value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected bool, got {}", value)))));
        });
    }

    /// Records a reading and returns the new sample count.
    pub fn record(&self, id: u64, value: f64, note: &str, valid: bool) -> Result<i64, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(value), serde_json::Value::from(note), serde_json::Value::from(valid)]);
        let value = self.proxy.call_json("record", &args)?;
        value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))
    }

    /// Async twin of [`Self::record`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `recordAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn record_async<F>(&self, id: u64, value: f64, note: &str, valid: bool, callback: F)
    where
        F: FnOnce(Result<i64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id), serde_json::Value::from(value), serde_json::Value::from(note), serde_json::Value::from(valid)]);
        self.proxy.call_json_async("record", &args, move |result| {
            callback(result.and_then(|value| value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected int, got {}", value)))));
        });
    }

    /// Flashes raw firmware bytes and echoes back the stored image.
    pub fn firmware(&self, image: &[u8]) -> Result<Vec<u8>, LogosError> {
        let args = serde_json::Value::Array(vec![logos_rust_sdk::bytes::encode(image)]);
        let value = self.proxy.call_json("firmware", &args)?;
        logos_rust_sdk::bytes::decode(&value).ok_or_else(|| logos_rust_sdk::LogosError::JsonError("expected {\"_bytes\":...} payload".to_string()))
    }

    /// Async twin of [`Self::firmware`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `firmwareAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn firmware_async<F>(&self, image: &[u8], callback: F)
    where
        F: FnOnce(Result<Vec<u8>, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![logos_rust_sdk::bytes::encode(image)]);
        self.proxy.call_json_async("firmware", &args, move |result| {
            callback(result.and_then(|value| logos_rust_sdk::bytes::decode(&value).ok_or_else(|| logos_rust_sdk::LogosError::JsonError("expected {\"_bytes\":...} payload".to_string()))));
        });
    }

    /// Resolves a batch of channel ids to their labels.
    pub fn labels(&self, ids: &serde_json::Value) -> Result<serde_json::Value, LogosError> {
        let args = serde_json::Value::Array(vec![ids.clone()]);
        let value = self.proxy.call_json("labels", &args)?;
        Ok(value)
    }

    /// Async twin of [`Self::labels`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `labelsAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn labels_async<F>(&self, ids: &serde_json::Value, callback: F)
    where
        F: FnOnce(Result<serde_json::Value, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![ids.clone()]);
        self.proxy.call_json_async("labels", &args, move |result| {
            callback(result.and_then(|value| Ok(value)));
        });
    }

    /// Computes the mean of a batch of samples.
    pub fn average(&self, samples: &serde_json::Value) -> Result<f64, LogosError> {
        let args = serde_json::Value::Array(vec![samples.clone()]);
        let value = self.proxy.call_json("average", &args)?;
        value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))
    }

    /// Async twin of [`Self::average`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `averageAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn average_async<F>(&self, samples: &serde_json::Value, callback: F)
    where
        F: FnOnce(Result<f64, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![samples.clone()]);
        self.proxy.call_json_async("average", &args, move |result| {
            callback(result.and_then(|value| value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!("expected float64, got {}", value)))));
        });
    }

    /// Resets a channel; returns a structured success/error result.
    pub fn reset(&self, id: &str) -> Result<serde_json::Value, LogosError> {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id)]);
        let value = self.proxy.call_json("reset", &args)?;
        Ok(value)
    }

    /// Async twin of [`Self::reset`]: fire the call and receive the typed
    /// result in `callback` once it lands — the Rust analog of the C++
    /// client's `resetAsync`. The callback runs from the protocol
    /// completion path (the module's Qt event loop), so it fires after
    /// the current method returns, never inline.
    pub fn reset_async<F>(&self, id: &str, callback: F)
    where
        F: FnOnce(Result<serde_json::Value, LogosError>) + Send + 'static,
    {
        let args = serde_json::Value::Array(vec![serde_json::Value::from(id)]);
        self.proxy.call_json_async("reset", &args, move |result| {
            callback(result.and_then(|value| Ok(value)));
        });
    }

    /// Fires once the sensor has finished warming up.
    /// Subscribe to the `ready` event. Payload arrives as a JSON array;
    /// decode each received item with [`Self::decode_ready`]. The returned
    /// subscription owns its client share — move it into a listener
    /// thread and iterate it; drop it to unsubscribe.
    pub fn on_ready(&mut self) -> Result<EventSubscription, LogosError> {
        self.proxy.on("ready")
    }

    /// Decode a received `ready` payload into its typed form.
    /// Returns None if the payload doesn't match the contract.
    pub fn decode_ready(ev: &EventData) -> Option<ReadyEvent> {
        let arr = ev.data.as_array()?;
        if arr.len() < 0 { return None; }
        Some(ReadyEvent {
        })
    }

    /// Fires on each new reading with the channel id and value.
    /// Subscribe to the `reading` event. Payload arrives as a JSON array of [id: uint, value: float64];
    /// decode each received item with [`Self::decode_reading`]. The returned
    /// subscription owns its client share — move it into a listener
    /// thread and iterate it; drop it to unsubscribe.
    pub fn on_reading(&mut self) -> Result<EventSubscription, LogosError> {
        self.proxy.on("reading")
    }

    /// Decode a received `reading` payload into its typed form.
    /// Returns None if the payload doesn't match the contract.
    pub fn decode_reading(ev: &EventData) -> Option<ReadingEvent> {
        let arr = ev.data.as_array()?;
        if arr.len() < 2 { return None; }
        Some(ReadingEvent {
            id: arr[0].as_u64()?,
            value: arr[1].as_f64()?,
        })
    }

    /// Fires when a channel faults.
    /// Carries an error code, a message, and whether the fault is fatal.
    /// Subscribe to the `fault` event. Payload arrives as a JSON array of [code: int, message: tstr, fatal: bool];
    /// decode each received item with [`Self::decode_fault`]. The returned
    /// subscription owns its client share — move it into a listener
    /// thread and iterate it; drop it to unsubscribe.
    pub fn on_fault(&mut self) -> Result<EventSubscription, LogosError> {
        self.proxy.on("fault")
    }

    /// Decode a received `fault` payload into its typed form.
    /// Returns None if the payload doesn't match the contract.
    pub fn decode_fault(ev: &EventData) -> Option<FaultEvent> {
        let arr = ev.data.as_array()?;
        if arr.len() < 3 { return None; }
        Some(FaultEvent {
            code: arr[0].as_i64()?,
            message: arr[1].as_str()?.to_string(),
            fatal: arr[2].as_bool()?,
        })
    }
}

/// Typed payload of the `ready` event.
#[derive(Debug, Clone)]
pub struct ReadyEvent {
}

/// Typed payload of the `reading` event.
#[derive(Debug, Clone)]
pub struct ReadingEvent {
    pub id: u64,
    pub value: f64,
}

/// Typed payload of the `fault` event.
#[derive(Debug, Clone)]
pub struct FaultEvent {
    pub code: i64,
    pub message: String,
    pub fatal: bool,
}

impl Default for SensorModuleClient {
    fn default() -> Self {
        Self::new()
    }
}
