// Generated by logos-lidl-gen --provider from the `geometry_module` LIDL contract — do not edit.
//
// The common module-impl C ABI (logos_module_impl.h) around a Rust impl:
// implement `GeometryModule` on your type and define the install hook:
//
//     #[no_mangle]
//     pub extern "Rust" fn logos_module_install() { install::<YourImpl>(); }
//
// The first dispatch invokes it lazily — a plain symbol reference, so
// no ctor/init-section tricks are needed for static linking.

use std::ffi::{c_char, c_int, c_void, CStr, CString};
use std::sync::Mutex;

#[derive(Debug, Clone, Default)]
pub struct RustModuleContext {
    pub module_path: String,
    pub instance_id: String,
    pub instance_persistence_path: String,
}

static CONTEXT: Mutex<Option<RustModuleContext>> = Mutex::new(None);

/// The module identity/context stamped by the host (None before
/// set_context — mirrors LogosModuleContext::isContextReady()).
pub fn context() -> Option<RustModuleContext> {
    CONTEXT.lock().unwrap().clone()
}

type EmitCb = extern "C" fn(*const c_char, *const c_char, *mut c_void);
struct EmitState {
    cb: Option<(EmitCb, usize)>,
}
unsafe impl Send for EmitState {}
static EMIT: Mutex<EmitState> = Mutex::new(EmitState { cb: None });

fn emit_event(name: &str, payload: &serde_json::Value) {
    let state = EMIT.lock().unwrap();
    if let Some((cb, ud)) = state.cb {
        let name_c = CString::new(name).unwrap_or_default();
        let json_c = CString::new(payload.to_string()).unwrap_or_default();
        cb(name_c.as_ptr(), json_c.as_ptr(), ud as *mut c_void);
    }
}

/// Typed emitter for the `moved` event.
pub fn emit_moved(from: &serde_json::Value, to: &serde_json::Value) {
    let mut payload: Vec<serde_json::Value> = Vec::new();
    payload.push(from.clone());
    payload.push(to.clone());
    emit_event("moved", &serde_json::Value::Array(payload));
}

pub trait GeometryModule: Send + 'static {
    /// One-time setup hook: fires after the host has stamped the module
    /// context (path / instance id / persistence path) and before the
    /// first method dispatch — the Rust analog of C++'s
    /// LogosModuleContext::onContextReady().
    fn on_context_ready(&mut self, _ctx: &RustModuleContext) {}

    fn translate(&mut self, p: serde_json::Value, dx: f64, dy: f64) -> serde_json::Value;
    fn bounds(&mut self, points: serde_json::Value) -> serde_json::Value;
    fn attributes(&mut self, tags: serde_json::Value) -> serde_json::Value;
    fn nearest(&mut self, p: serde_json::Value, limit: serde_json::Value) -> serde_json::Value;
    fn describe(&mut self, p: serde_json::Value) -> serde_json::Value;
}

type DispatchFn = fn(&str, &[serde_json::Value]) -> Option<serde_json::Value>;
type EnsureFn = fn(bool);
struct Registered {
    dispatch: DispatchFn,
    ensure: EnsureFn,
}
static REGISTERED: Mutex<Option<Registered>> = Mutex::new(None);
static INSTANCE: Mutex<Option<Box<dyn std::any::Any + Send>>> = Mutex::new(None);
static HOOK_FIRED: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);

/// Install `T` as the module implementation (Default-constructed once).
///
/// `on_context_ready` fires AT MODULE LOAD — as soon as the host has
/// delivered both the context (set_context) and the event plumbing
/// (set_emit_callback), which the glue does during registration,
/// before the module is published for inbound calls. This matches
/// C++'s onContextReady-in-onInit semantics: subscriptions, outbound
/// calls and typed emission all work from the hook without waiting
/// for a first inbound dispatch. (For hosts that never wire an emit
/// callback, the hook still fires before the first dispatch.)
pub fn install<T: GeometryModule + Default>() {
    fn ensure_impl<T: GeometryModule + Default>(require_emit: bool) {
        let mut guard = INSTANCE.lock().unwrap();
        if guard.is_none() {
            *guard = Some(Box::new(T::default()));
        }
        if HOOK_FIRED.load(std::sync::atomic::Ordering::SeqCst) {
            return;
        }
        let Some(ctx) = context() else { return; };
        if require_emit && EMIT.lock().unwrap().cb.is_none() {
            return;
        }
        if let Some(imp) = guard.as_mut().unwrap().downcast_mut::<T>() {
            HOOK_FIRED.store(true, std::sync::atomic::Ordering::SeqCst);
            imp.on_context_ready(&ctx);
        }
    }
    fn dispatch_impl<T: GeometryModule + Default>(method: &str, args: &[serde_json::Value]) -> Option<serde_json::Value> {
        let mut guard = INSTANCE.lock().unwrap();
        if guard.is_none() {
            *guard = Some(Box::new(T::default()));
        }
        let imp: &mut T = guard.as_mut().unwrap().downcast_mut::<T>()?;
        match method {
            "translate" => {
                if args.len() < 3 { return None; }
                let result = imp.translate(args.get(0).unwrap_or(&serde_json::Value::Null).clone(), args.get(1).unwrap_or(&serde_json::Value::Null).as_f64().unwrap_or_default(), args.get(2).unwrap_or(&serde_json::Value::Null).as_f64().unwrap_or_default());
                Some(serde_json::Value::from(result))
            }
            "bounds" => {
                if args.len() < 1 { return None; }
                let result = imp.bounds(args.get(0).unwrap_or(&serde_json::Value::Null).clone());
                Some(serde_json::Value::from(result))
            }
            "attributes" => {
                if args.len() < 1 { return None; }
                let result = imp.attributes(args.get(0).unwrap_or(&serde_json::Value::Null).clone());
                Some(serde_json::Value::from(result))
            }
            "nearest" => {
                if args.len() < 2 { return None; }
                let result = imp.nearest(args.get(0).unwrap_or(&serde_json::Value::Null).clone(), args.get(1).unwrap_or(&serde_json::Value::Null).clone());
                Some(serde_json::Value::from(result))
            }
            "describe" => {
                if args.len() < 1 { return None; }
                let result = imp.describe(args.get(0).unwrap_or(&serde_json::Value::Null).clone());
                Some(serde_json::Value::from(result))
            }
            _ => None,
        }
    }
    *REGISTERED.lock().unwrap() = Some(Registered {
        dispatch: dispatch_impl::<T>,
        ensure: ensure_impl::<T>,
    });
}

/// Run the author's install hook (once) and give the ready-latch a
/// chance to fire `on_context_ready`. Called from every C-ABI entry
/// point: set_context / set_emit_callback latch on full wiring;
/// dispatch passes require_emit = false as the no-event-host fallback.
fn ensure_ready(require_emit: bool) {
    if REGISTERED.lock().unwrap().is_none() {
        unsafe { __logos_install_hook::logos_module_install() };
    }
    let ensure = REGISTERED.lock().unwrap().as_ref().map(|r| r.ensure);
    if let Some(f) = ensure {
        f(require_emit);
    }
}

mod __logos_install_hook {
    // Defined by the module author (a #[no_mangle] fn at crate root):
    // call `install::<YourImpl>()` once. Scoped inside a module so the
    // declaration and the author's definition don't collide by path;
    // they meet at the symbol level. Referenced (not just expected) so
    // static linking always pulls the author's object in — invoked
    // lazily on first dispatch.
    extern "Rust" {
        pub(super) fn logos_module_install();
    }
}

fn to_c_string(s: String) -> *mut c_char {
    CString::new(s).map(CString::into_raw).unwrap_or(std::ptr::null_mut())
}

#[no_mangle]
pub extern "C" fn logos_module_dispatch(method: *const c_char, args_json: *const c_char) -> *mut c_char {
    if method.is_null() { return std::ptr::null_mut(); }
    let method = unsafe { CStr::from_ptr(method) }.to_string_lossy().into_owned();
    let args: Vec<serde_json::Value> = if args_json.is_null() {
        Vec::new()
    } else {
        let raw = unsafe { CStr::from_ptr(args_json) }.to_string_lossy();
        match serde_json::from_str::<serde_json::Value>(&raw) {
            Ok(serde_json::Value::Array(a)) => a,
            _ => return std::ptr::null_mut(),
        }
    };
    ensure_ready(false);
    let guard = REGISTERED.lock().unwrap();
    let registered = match guard.as_ref() { Some(r) => r, None => return std::ptr::null_mut() };
    match (registered.dispatch)(&method, &args) {
        Some(value) => to_c_string(value.to_string()),
        None => std::ptr::null_mut(),
    }
}

#[no_mangle]
pub extern "C" fn logos_module_get_methods() -> *mut c_char {
    to_c_string("[{\"isInvokable\":true,\"name\":\"translate\",\"parameters\":[{\"name\":\"p\",\"type\":\"QVariant\"},{\"name\":\"dx\",\"type\":\"double\"},{\"name\":\"dy\",\"type\":\"double\"}],\"returnType\":\"QVariant\",\"signature\":\"translate(QVariant,double,double)\"},{\"isInvokable\":true,\"name\":\"bounds\",\"parameters\":[{\"name\":\"points\",\"type\":\"QVariantList\"}],\"returnType\":\"QVariant\",\"signature\":\"bounds(QVariantList)\"},{\"isInvokable\":true,\"name\":\"attributes\",\"parameters\":[{\"name\":\"tags\",\"type\":\"QVariantMap\"}],\"returnType\":\"QVariantMap\",\"signature\":\"attributes(QVariantMap)\"},{\"isInvokable\":true,\"name\":\"nearest\",\"parameters\":[{\"name\":\"p\",\"type\":\"QVariant\"},{\"name\":\"limit\",\"type\":\"QVariant\"}],\"returnType\":\"QVariant\",\"signature\":\"nearest(QVariant,QVariant)\"},{\"isInvokable\":true,\"name\":\"describe\",\"parameters\":[{\"name\":\"p\",\"type\":\"QVariant\"}],\"returnType\":\"QVariant\",\"signature\":\"describe(QVariant)\"},{\"name\":\"moved\",\"parameters\":[{\"name\":\"from\",\"type\":\"QVariant\"},{\"name\":\"to\",\"type\":\"QVariant\"}],\"signature\":\"moved(QVariant,QVariant)\",\"type\":\"event\"}]".to_string())
}

#[no_mangle]
pub extern "C" fn logos_module_set_context(
    module_path: *const c_char,
    instance_id: *const c_char,
    instance_persistence_path: *const c_char,
) {
    fn s(p: *const c_char) -> String {
        if p.is_null() { String::new() } else { unsafe { CStr::from_ptr(p) }.to_string_lossy().into_owned() }
    }
    *CONTEXT.lock().unwrap() = Some(RustModuleContext {
        module_path: s(module_path),
        instance_id: s(instance_id),
        instance_persistence_path: s(instance_persistence_path),
    });
    ensure_ready(true);
}

#[no_mangle]
pub extern "C" fn logos_module_set_emit_callback(cb: Option<EmitCb>, user_data: *mut c_void) {
    EMIT.lock().unwrap().cb = cb.map(|f| (f, user_data as usize));
    ensure_ready(true);
}

static TOKENS: Mutex<Vec<(String, String)>> = Mutex::new(Vec::new());

#[no_mangle]
pub extern "C" fn logos_module_accept_token(module_name: *const c_char, token: *const c_char) -> c_int {
    if module_name.is_null() || token.is_null() { return -1; }
    let name = unsafe { CStr::from_ptr(module_name) }.to_string_lossy().into_owned();
    let tok = unsafe { CStr::from_ptr(token) }.to_string_lossy().into_owned();
    // The runtime handshake: hand the host-issued token to the SDK's
    // protocol stack so this module's *outbound* calls authenticate —
    // the same stack the typed client wrappers invoke through.
    logos_rust_sdk::save_token(&name, &tok);
    TOKENS.lock().unwrap().push((name, tok));
    0
}

/// The logos-protocol semver this module was built against
/// (stamped at generation time by the build; never minted here).
#[no_mangle]
pub extern "C" fn logos_module_get_protocol_version() -> *const c_char {
    static VERSION: &str = "0.1.0\0";
    VERSION.as_ptr() as *const c_char
}

#[no_mangle]
pub extern "C" fn logos_module_string_free(s: *mut c_char) {
    if !s.is_null() {
        unsafe { drop(CString::from_raw(s)) };
    }
}
