// Generated by logos-lidl-gen --provider from the `geometry_module` LIDL contract — do not edit.
//
// The common module-impl C ABI (logos_module_impl.h) around a Rust impl:
// implement `GeometryModule` on your type and define the install hook:
//
//     #[no_mangle]
//     pub extern "Rust" fn logos_module_install() { install::<YourImpl>(); }
//
// The first dispatch invokes it lazily — a plain symbol reference, so
// no ctor/init-section tricks are needed for static linking.

use std::ffi::{c_char, c_int, c_void, CStr, CString};
use std::sync::Mutex;

#[derive(Debug, Clone, Default)]
pub struct RustModuleContext {
    pub module_path: String,
    pub instance_id: String,
    pub instance_persistence_path: String,
}

static CONTEXT: Mutex<Option<RustModuleContext>> = Mutex::new(None);

/// The module identity/context stamped by the host (None before
/// set_context — mirrors LogosModuleContext::isContextReady()).
pub fn context() -> Option<RustModuleContext> {
    CONTEXT.lock().unwrap().clone()
}

type EmitCb = extern "C" fn(*const c_char, *const c_char, *mut c_void);
struct EmitState {
    cb: Option<(EmitCb, usize)>,
}
unsafe impl Send for EmitState {}
static EMIT: Mutex<EmitState> = Mutex::new(EmitState { cb: None });

fn emit_event(name: &str, payload: &serde_json::Value) {
    let state = EMIT.lock().unwrap();
    if let Some((cb, ud)) = state.cb {
        let name_c = CString::new(name).unwrap_or_default();
        let json_c = CString::new(payload.to_string()).unwrap_or_default();
        cb(name_c.as_ptr(), json_c.as_ptr(), ud as *mut c_void);
    }
}

/// Typed emitter for the `moved` event.
pub fn emit_moved(from: &Point, to: &Point) {
    let mut __logos_args: Vec<serde_json::Value> = Vec::new();
    __logos_args.push(from.to_json());
    __logos_args.push(to.to_json());
    emit_event("moved", &serde_json::Value::Array(__logos_args));
}

/// `Point` — a record declared by the `geometry_module` contract.
#[derive(Debug, Clone, PartialEq)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

impl Point {
    /// The record as its canonical JSON object.
    pub fn to_json(&self) -> serde_json::Value {
        let mut o = serde_json::Map::new();
        o.insert("x".to_string(), serde_json::json!(self.x));
        o.insert("y".to_string(), serde_json::json!(self.y));
        serde_json::Value::Object(o)
    }

    /// Decode the canonical JSON object. None if a field is missing or
    /// has the wrong shape — the provider reports the same mismatch with
    /// a field path, so this is the consumer-side half of that contract.
    pub fn from_json(v: &serde_json::Value) -> Option<Self> {
        let o = v.as_object()?;
        Some(Self {
            x: o.get("x")?.as_f64()?,
            y: o.get("y")?.as_f64()?,
        })
    }
}

pub trait GeometryModule: 'static {
    /// One-time setup hook: fires after the host has stamped the module
    /// context (path / instance id / persistence path) and before the
    /// first method dispatch — the Rust analog of C++'s
    /// LogosModuleContext::onContextReady().
    fn on_context_ready(&mut self, _ctx: &RustModuleContext) {}

    fn translate(&mut self, p: Point, dx: f64, dy: f64) -> Point;
    fn bounds(&mut self, points: Vec<Point>) -> Point;
    fn attributes(&mut self, tags: serde_json::Value) -> serde_json::Value;
    fn nearest(&mut self, p: Point, limit: Option<u64>) -> Option<Point>;
    fn describe(&mut self, p: Point) -> serde_json::Value;
}

type DispatchFn = fn(&str, &[serde_json::Value]) -> Option<serde_json::Value>;
type EnsureFn = fn(bool);
struct Registered {
    dispatch: DispatchFn,
    ensure: EnsureFn,
}
static REGISTERED: Mutex<Option<Registered>> = Mutex::new(None);
// A concurrency:"single" module runs entirely on one thread (its
// subprocess event loop): install / on_context_ready / dispatch all touch
// INSTANCE from that thread, so the impl never crosses threads and need
// not be Send. This single-threaded Sync wrapper lets a non-Send impl
// live in a static (cf. the EmitState unsafe impl above).
struct SingleInstance(Mutex<Option<Box<dyn std::any::Any>>>);
unsafe impl Sync for SingleInstance {}
static INSTANCE: SingleInstance = SingleInstance(Mutex::new(None));
static HOOK_FIRED: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);

/// Install `T` as the module implementation (Default-constructed once).
///
/// `on_context_ready` fires AT MODULE LOAD — as soon as the host has
/// delivered both the context (set_context) and the event plumbing
/// (set_emit_callback), which the glue does during registration,
/// before the module is published for inbound calls. This matches
/// C++'s onContextReady-in-onInit semantics: subscriptions, outbound
/// calls and typed emission all work from the hook without waiting
/// for a first inbound dispatch. (For hosts that never wire an emit
/// callback, the hook still fires before the first dispatch.)
pub fn install<T: GeometryModule + Default>() {
    fn ensure_impl<T: GeometryModule + Default>(require_emit: bool) {
        let mut guard = INSTANCE.0.lock().unwrap();
        if guard.is_none() {
            *guard = Some(Box::new(T::default()));
        }
        if HOOK_FIRED.load(std::sync::atomic::Ordering::SeqCst) {
            return;
        }
        let Some(ctx) = context() else { return; };
        if require_emit && EMIT.lock().unwrap().cb.is_none() {
            return;
        }
        if let Some(imp) = guard.as_mut().unwrap().downcast_mut::<T>() {
            HOOK_FIRED.store(true, std::sync::atomic::Ordering::SeqCst);
            imp.on_context_ready(&ctx);
        }
    }
    fn dispatch_impl<T: GeometryModule + Default>(method: &str, args: &[serde_json::Value]) -> Option<serde_json::Value> {
        let mut guard = INSTANCE.0.lock().unwrap();
        if guard.is_none() {
            *guard = Some(Box::new(T::default()));
        }
        let imp: &mut T = guard.as_mut().unwrap().downcast_mut::<T>()?;
        match method {
            "translate" => {
                if args.len() < 3 { return Some(logos_rust_sdk::args::invalid_args("geometry_module", 3, args.len())); }
                let __logos_a0 = match logos_rust_sdk::args::as_value_checked(args, 0, &logos_rust_sdk::args::Ty::Record(&[("x", &logos_rust_sdk::args::Ty::Float64), ("y", &logos_rust_sdk::args::Ty::Float64)])) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", &e)) };
                let __logos_a0 = match Point::from_json(&__logos_a0) { Some(v) => v, None => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", "arg0: malformed record")) };
                let __logos_a1 = match logos_rust_sdk::args::as_f64(args, 1) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", &e)) };
                let __logos_a2 = match logos_rust_sdk::args::as_f64(args, 2) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", &e)) };
                let result = imp.translate(__logos_a0, __logos_a1, __logos_a2);
                Some(result.to_json())
            }
            "bounds" => {
                if args.len() < 1 { return Some(logos_rust_sdk::args::invalid_args("geometry_module", 1, args.len())); }
                let __logos_a0 = match logos_rust_sdk::args::as_value_checked(args, 0, &logos_rust_sdk::args::Ty::Arr(&logos_rust_sdk::args::Ty::Record(&[("x", &logos_rust_sdk::args::Ty::Float64), ("y", &logos_rust_sdk::args::Ty::Float64)]))) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", &e)) };
                let __logos_a0 = match __logos_a0.as_array().and_then(|__a| __a.iter().map(Point::from_json).collect::<Option<Vec<_>>>()) { Some(v) => v, None => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", "arg0: malformed record")) };
                let result = imp.bounds(__logos_a0);
                Some(result.to_json())
            }
            "attributes" => {
                if args.len() < 1 { return Some(logos_rust_sdk::args::invalid_args("geometry_module", 1, args.len())); }
                let __logos_a0 = match logos_rust_sdk::args::as_value_checked(args, 0, &logos_rust_sdk::args::Ty::Map(&logos_rust_sdk::args::Ty::Any)) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", &e)) };
                let result = imp.attributes(__logos_a0);
                Some(serde_json::Value::from(result))
            }
            "nearest" => {
                if args.len() < 1 { return Some(logos_rust_sdk::args::invalid_args("geometry_module", 1, args.len())); }
                let __logos_a0 = match logos_rust_sdk::args::as_value_checked(args, 0, &logos_rust_sdk::args::Ty::Record(&[("x", &logos_rust_sdk::args::Ty::Float64), ("y", &logos_rust_sdk::args::Ty::Float64)])) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", &e)) };
                let __logos_a0 = match Point::from_json(&__logos_a0) { Some(v) => v, None => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", "arg0: malformed record")) };
                let __logos_a1 = match logos_rust_sdk::args::as_opt_u64(args, 1) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", &e)) };
                let result = imp.nearest(__logos_a0, __logos_a1);
                Some(match result { Some(__o) => __o.to_json(), None => serde_json::Value::Null })
            }
            "describe" => {
                if args.len() < 1 { return Some(logos_rust_sdk::args::invalid_args("geometry_module", 1, args.len())); }
                let __logos_a0 = match logos_rust_sdk::args::as_value_checked(args, 0, &logos_rust_sdk::args::Ty::Record(&[("x", &logos_rust_sdk::args::Ty::Float64), ("y", &logos_rust_sdk::args::Ty::Float64)])) { Ok(v) => v, Err(e) => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", &e)) };
                let __logos_a0 = match Point::from_json(&__logos_a0) { Some(v) => v, None => return Some(logos_rust_sdk::args::dispatch_failed("geometry_module", "arg0: malformed record")) };
                let result = imp.describe(__logos_a0);
                Some(serde_json::Value::from(result))
            }
            _ => None,
        }
    }
    *REGISTERED.lock().unwrap() = Some(Registered {
        dispatch: dispatch_impl::<T>,
        ensure: ensure_impl::<T>,
    });
}

/// Run the author's install hook (once) and give the ready-latch a
/// chance to fire `on_context_ready`. Called from every C-ABI entry
/// point: set_context / set_emit_callback latch on full wiring;
/// dispatch passes require_emit = false as the no-event-host fallback.
fn ensure_ready(require_emit: bool) {
    if REGISTERED.lock().unwrap().is_none() {
        unsafe { __logos_install_hook::logos_module_install() };
    }
    let ensure = REGISTERED.lock().unwrap().as_ref().map(|r| r.ensure);
    if let Some(f) = ensure {
        f(require_emit);
    }
}

mod __logos_install_hook {
    // Defined by the module author (a #[no_mangle] fn at crate root):
    // call `install::<YourImpl>()` once. Scoped inside a module so the
    // declaration and the author's definition don't collide by path;
    // they meet at the symbol level. Referenced (not just expected) so
    // static linking always pulls the author's object in — invoked
    // lazily on first dispatch.
    extern "Rust" {
        pub(super) fn logos_module_install();
    }
}

fn to_c_string(s: String) -> *mut c_char {
    CString::new(s).map(CString::into_raw).unwrap_or(std::ptr::null_mut())
}

#[no_mangle]
pub extern "C" fn logos_module_dispatch(method: *const c_char, args_json: *const c_char) -> *mut c_char {
    if method.is_null() { return std::ptr::null_mut(); }
    let method = unsafe { CStr::from_ptr(method) }.to_string_lossy().into_owned();
    let args: Vec<serde_json::Value> = if args_json.is_null() {
        Vec::new()
    } else {
        let raw = unsafe { CStr::from_ptr(args_json) }.to_string_lossy();
        match serde_json::from_str::<serde_json::Value>(&raw) {
            Ok(serde_json::Value::Array(a)) => a,
            _ => return std::ptr::null_mut(),
        }
    };
    ensure_ready(false);
    // Copy the dispatch fn pointer out and RELEASE the REGISTERED
    // lock BEFORE running the handler. A concurrency:"multi" module's
    // glue calls this from worker threads; holding the mutex across
    // the handler would serialize every call (peak overlap 1).
    // dispatch_impl resolves the instance internally (a cloned Arc in
    // multi mode, the boxed instance behind the SingleInstance mutex in
    // single mode) without holding REGISTERED, so dropping the lock here
    // first is safe. Same release-before-call shape as ensure_ready.
    let dispatch = match REGISTERED.lock().unwrap().as_ref() { Some(r) => r.dispatch, None => return std::ptr::null_mut() };
    match dispatch(&method, &args) {
        Some(value) => to_c_string(value.to_string()),
        None => std::ptr::null_mut(),
    }
}

#[no_mangle]
pub extern "C" fn logos_module_get_methods() -> *mut c_char {
    to_c_string("[{\"isInvokable\":true,\"name\":\"translate\",\"parameters\":[{\"name\":\"p\",\"type\":\"QVariant\"},{\"name\":\"dx\",\"type\":\"double\"},{\"name\":\"dy\",\"type\":\"double\"}],\"returnType\":\"QVariant\",\"signature\":\"translate(QVariant,double,double)\"},{\"isInvokable\":true,\"name\":\"bounds\",\"parameters\":[{\"name\":\"points\",\"type\":\"QVariantList\"}],\"returnType\":\"QVariant\",\"signature\":\"bounds(QVariantList)\"},{\"isInvokable\":true,\"name\":\"attributes\",\"parameters\":[{\"name\":\"tags\",\"type\":\"QVariantMap\"}],\"returnType\":\"QVariantMap\",\"signature\":\"attributes(QVariantMap)\"},{\"isInvokable\":true,\"name\":\"nearest\",\"parameters\":[{\"name\":\"p\",\"type\":\"QVariant\"},{\"name\":\"limit\",\"type\":\"QVariant\"}],\"returnType\":\"QVariant\",\"signature\":\"nearest(QVariant,QVariant)\"},{\"isInvokable\":true,\"name\":\"describe\",\"parameters\":[{\"name\":\"p\",\"type\":\"QVariant\"}],\"returnType\":\"QVariant\",\"signature\":\"describe(QVariant)\"},{\"name\":\"moved\",\"parameters\":[{\"name\":\"from\",\"type\":\"QVariant\"},{\"name\":\"to\",\"type\":\"QVariant\"}],\"signature\":\"moved(QVariant,QVariant)\",\"type\":\"event\"}]".to_string())
}

#[no_mangle]
pub extern "C" fn logos_module_set_context(
    module_path: *const c_char,
    instance_id: *const c_char,
    instance_persistence_path: *const c_char,
) {
    fn s(p: *const c_char) -> String {
        if p.is_null() { String::new() } else { unsafe { CStr::from_ptr(p) }.to_string_lossy().into_owned() }
    }
    *CONTEXT.lock().unwrap() = Some(RustModuleContext {
        module_path: s(module_path),
        instance_id: s(instance_id),
        instance_persistence_path: s(instance_persistence_path),
    });
    ensure_ready(true);
}

#[no_mangle]
pub extern "C" fn logos_module_set_emit_callback(cb: Option<EmitCb>, user_data: *mut c_void) {
    EMIT.lock().unwrap().cb = cb.map(|f| (f, user_data as usize));
    ensure_ready(true);
}

static TOKENS: Mutex<Vec<(String, String)>> = Mutex::new(Vec::new());

#[no_mangle]
pub extern "C" fn logos_module_accept_token(module_name: *const c_char, token: *const c_char) -> c_int {
    if module_name.is_null() || token.is_null() { return -1; }
    let name = unsafe { CStr::from_ptr(module_name) }.to_string_lossy().into_owned();
    let tok = unsafe { CStr::from_ptr(token) }.to_string_lossy().into_owned();
    // The runtime handshake: hand the host-issued token to the SDK's
    // protocol stack so this module's *outbound* calls authenticate —
    // the same stack the typed client wrappers invoke through.
    logos_rust_sdk::save_token(&name, &tok);
    TOKENS.lock().unwrap().push((name, tok));
    0
}

/// The logos-protocol semver this module was built against
/// (stamped at generation time by the build; never minted here).
#[no_mangle]
pub extern "C" fn logos_module_get_protocol_version() -> *const c_char {
    static VERSION: &str = "0.1.0\0";
    VERSION.as_ptr() as *const c_char
}

#[no_mangle]
pub extern "C" fn logos_module_string_free(s: *mut c_char) {
    if !s.is_null() {
        unsafe { drop(CString::from_raw(s)) };
    }
}
