//! Rust code generation: a typed client struct per LIDL module.

use crate::ast::*;

fn pascal(name: &str) -> String {
    name.split('_')
        .filter(|s| !s.is_empty())
        .map(|s| {
            let mut c = s.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn snake(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// Rust parameter type for a LIDL type.
fn param_type(ty: &TypeExpr) -> &'static str {
    match (&ty.kind, ty.name.as_str()) {
        (TypeKind::Primitive, "tstr") => "&str",
        (TypeKind::Primitive, "int") => "i64",
        (TypeKind::Primitive, "uint") => "u64",
        (TypeKind::Primitive, "float64") => "f64",
        (TypeKind::Primitive, "bool") => "bool",
        (TypeKind::Primitive, "bstr") => "&[u8]",
        // result/any, arrays, maps, optionals and named types travel as JSON.
        _ => "&serde_json::Value",
    }
}

/// Expression converting a parameter into its JSON wire value.
fn param_to_json(name: &str, ty: &TypeExpr) -> String {
    match (&ty.kind, ty.name.as_str()) {
        (TypeKind::Primitive, "bstr") => format!("logos_rust_sdk::bytes::encode({})", name),
        (TypeKind::Primitive, "tstr") => format!("serde_json::Value::from({})", name),
        (TypeKind::Primitive, "int") | (TypeKind::Primitive, "uint")
        | (TypeKind::Primitive, "float64") | (TypeKind::Primitive, "bool") => {
            format!("serde_json::Value::from({})", name)
        }
        _ => format!("{}.clone()", name),
    }
}

/// (return type, conversion-from-json expression over `value`)
fn return_conv(ty: &TypeExpr) -> (String, String) {
    match (&ty.kind, ty.name.as_str()) {
        (TypeKind::Primitive, "tstr") => (
            "String".into(),
            "Ok(value.as_str().unwrap_or_default().to_string())".into(),
        ),
        (TypeKind::Primitive, "int") => (
            "i64".into(),
            "value.as_i64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!(\"expected int, got {}\", value)))".into(),
        ),
        (TypeKind::Primitive, "uint") => (
            "u64".into(),
            "value.as_u64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!(\"expected uint, got {}\", value)))".into(),
        ),
        (TypeKind::Primitive, "float64") => (
            "f64".into(),
            "value.as_f64().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!(\"expected float64, got {}\", value)))".into(),
        ),
        (TypeKind::Primitive, "bool") => (
            "bool".into(),
            "value.as_bool().ok_or_else(|| logos_rust_sdk::LogosError::JsonError(format!(\"expected bool, got {}\", value)))".into(),
        ),
        (TypeKind::Primitive, "bstr") => (
            "Vec<u8>".into(),
            "logos_rust_sdk::bytes::decode(&value).ok_or_else(|| logos_rust_sdk::LogosError::JsonError(\"expected {\\\"_bytes\\\":...} payload\".to_string()))".into(),
        ),
        _ => ("serde_json::Value".into(), "Ok(value)".into()),
    }
}

/// Generate the typed Rust client for a LIDL module.
pub fn generate(module: &ModuleDecl) -> String {
    let struct_name = format!("{}Client", pascal(&module.name));
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by logos-lidl-gen from the `{}` LIDL contract — do not edit.\n\
         //\n\
         // Typed caller + event subscribers over logos_rust_sdk's lp_* consumer.\n\n\
         use logos_rust_sdk::{{EventData, LogosError, LogosModuleSDK, PluginProxy}};\n\
         use std::sync::mpsc::Receiver;\n\n",
        module.name
    ));

    out.push_str(&format!("pub struct {} {{\n    proxy: PluginProxy,\n}}\n\n", struct_name));
    out.push_str(&format!("impl {} {{\n", struct_name));
    out.push_str(&format!(
        "    pub fn new() -> Self {{\n        Self {{ proxy: LogosModuleSDK::new().plugin(\"{}\") }}\n    }}\n",
        module.name
    ));

    for m in &module.methods {
        let fn_name = snake(&m.name);
        let params_sig: Vec<String> = m
            .params
            .iter()
            .map(|p| format!("{}: {}", snake(&p.name), param_type(&p.ty)))
            .collect();
        let args: Vec<String> = m
            .params
            .iter()
            .map(|p| param_to_json(&snake(&p.name), &p.ty))
            .collect();
        let (ret_ty, conv) = return_conv(&m.return_type);
        out.push_str(&format!(
            "\n    pub fn {}(&self{}{}) -> Result<{}, LogosError> {{\n\
             \x20       let args = serde_json::Value::Array(vec![{}]);\n\
             \x20       let value = self.proxy.call_json(\"{}\", &args)?;\n\
             \x20       {}\n\
             \x20   }}\n",
            fn_name,
            if params_sig.is_empty() { "" } else { ", " },
            params_sig.join(", "),
            ret_ty,
            args.join(", "),
            m.name,
            conv
        ));
    }

    for e in &module.events {
        out.push_str(&format!(
            "\n    /// Subscribe to the `{}` event. Payload arrives as a JSON array{}.\n\
             \x20   pub fn on_{}(&mut self) -> Result<Receiver<EventData>, LogosError> {{\n\
             \x20       self.proxy.on(\"{}\")\n\
             \x20   }}\n",
            e.name,
            if e.params.is_empty() {
                String::new()
            } else {
                format!(
                    " of [{}]",
                    e.params
                        .iter()
                        .map(|p| format!("{}: {}", p.name, p.ty.name))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            },
            snake(&e.name),
            e.name
        ));
    }

    out.push_str("}\n\n");
    out.push_str(&format!(
        "impl Default for {} {{\n    fn default() -> Self {{\n        Self::new()\n    }}\n}}\n",
        struct_name
    ));
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;

    const SAMPLE: &str = r#"
module calc_module {
  version "1.0.0"
  depends []
  method add(a: int, b: int) -> int
  method describe(name: tstr) -> tstr
  method store(data: bstr) -> bool
  method dump() -> any
  event resultReady(total: int)
}
"#;

    #[test]
    fn generates_typed_client() {
        let m = parse(SAMPLE).unwrap();
        let code = generate(&m);
        assert!(code.contains("pub struct CalcModuleClient"));
        assert!(code.contains("pub fn add(&self, a: i64, b: i64) -> Result<i64, LogosError>"));
        assert!(code.contains("pub fn describe(&self, name: &str) -> Result<String, LogosError>"));
        assert!(code.contains("pub fn store(&self, data: &[u8]) -> Result<bool, LogosError>"));
        assert!(code.contains("logos_rust_sdk::bytes::encode(data)"));
        assert!(code.contains("pub fn dump(&self) -> Result<serde_json::Value, LogosError>"));
        assert!(code.contains("pub fn on_result_ready(&mut self)"));
        assert!(code.contains("self.proxy.call_json(\"add\", &args)"));
    }

    #[test]
    fn parser_handles_keywords_as_names() {
        let m = parse("module module { depends [] method method(version: tstr) -> bool }").unwrap();
        assert_eq!(m.name, "module");
        assert_eq!(m.methods[0].name, "method");
        assert_eq!(m.methods[0].params[0].name, "version");
    }

    #[test]
    fn parser_full_grammar() {
        let m = parse(
            "module x { version \"2.0.0\" depends [a, b] \
             type T { id: tstr ? blob: bstr tags: [tstr] meta: {tstr: any} } \
             method f(t: T, n: ? int) -> result \
             event e(payload: bstr) }",
        )
        .unwrap();
        assert_eq!(m.depends, vec!["a", "b"]);
        assert_eq!(m.types[0].fields.len(), 4);
        assert!(m.types[0].fields[1].optional);
        assert_eq!(m.methods[0].params[1].ty.kind, TypeKind::Optional);
        assert_eq!(m.events[0].params[0].ty.name, "bstr");
    }
}
