//! Rust CONSUMER on the builder-driven cdylib path (no build.rs). Shows the
//! whole Rust-SDK surface:
//!   - a CONCRETE dependency (modules().rust_calc_module) — sync AND async calls
//!   - an INTERFACE dependency (the `greeter` contract bound to a concrete
//!     provider at runtime via GreeterClient::bind)
//!   - module CONTEXT (module_path / instance_id / instance_persistence_path)
//!   - typed event SUBSCRIPTION to the calc provider's `computed` event
//! The trait, the typed dependency clients, modules(), and RustModuleContext
//! are all generated by the builder from the contracts.

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/generated/provider_gen.rs"));

// Results that arrive on the event loop (async completion, event delivery)
// land here; the module reads them back through its own methods. The generated
// scaffold already imports Mutex, so refer to it by full path.
static LAST_ASYNC: std::sync::Mutex<i64> = std::sync::Mutex::new(-1);
static LAST_COMPUTED: std::sync::Mutex<i64> = std::sync::Mutex::new(-1);

#[derive(Default)]
struct Orchestrator;

impl RustOrchestratorModule for Orchestrator {
    /// SYNC typed call to the concrete dependency.
    fn tally(&mut self, a: i64, b: i64) -> i64 {
        modules().rust_calc_module.add(a, b).unwrap_or(-1)
    }

    /// ASYNC typed call: fire and return immediately; the typed result lands on
    /// the event loop and is stashed for `last_async()` to read.
    fn tally_async(&mut self, a: i64, b: i64) -> i64 {
        modules().rust_calc_module.add_async(a, b, |res| {
            if let Ok(v) = res {
                *LAST_ASYNC.lock().unwrap() = v;
            }
        });
        0
    }

    fn last_async(&mut self) -> i64 {
        *LAST_ASYNC.lock().unwrap()
    }

    /// INTERFACE dependency: the `greeter` contract bound to a concrete provider
    /// module chosen at runtime — the consumer codes against the shape, not the
    /// module.
    fn hello(&mut self, name: String) -> String {
        greeter::GreeterClient::bind("cpp_greeter_module")
            .greet(&name)
            .unwrap_or_else(|e| format!("greet failed: {}", e))
    }

    /// Module CONTEXT: the three host-stamped identity fields.
    fn whereami(&mut self) -> String {
        match context() {
            Some(c) => format!(
                "module_path={} | instance_id={} | persistence={}",
                c.module_path, c.instance_id, c.instance_persistence_path
            ),
            None => "context not ready".to_string(),
        }
    }

    fn last_computed(&mut self) -> i64 {
        *LAST_COMPUTED.lock().unwrap()
    }

    /// One-time setup once the host stamps the context. Subscribe to the calc
    /// provider's typed `computed` event; the subscription owns its client
    /// share, so move it into a listener thread.
    fn on_context_ready(&mut self, ctx: &RustModuleContext) {
        eprintln!(
            "orchestrator ready: module_path={} instance_id={} persistence={}",
            ctx.module_path, ctx.instance_id, ctx.instance_persistence_path
        );
        let mut calc = modules().rust_calc_module;
        if let Ok(sub) = calc.on_computed() {
            std::thread::spawn(move || {
                for ev in sub {
                    if let Some(e) = rust_calc_module::RustCalcModuleClient::decode_computed(&ev) {
                        *LAST_COMPUTED.lock().unwrap() = e.total;
                    }
                }
            });
        }
    }
}

#[no_mangle]
pub extern "Rust" fn logos_module_install() {
    install::<Orchestrator>();
}
